#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;
require "vendor/autoload.php";

$app = new Application("Task App", "1.0.0");

try{
    $pdo = new PDO('sqlite:db.sqlite');
    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
}catch(Exception $exception){
    echo "Could not connect to the database \n";
    echo $exception->getMessage();
    exit(1);
}

$dbAdapter = new Shuv\DatabaseAdapter($pdo);

$app->add(new Shuv\ShowCommand($dbAdapter));
$app->add(new Shuv\AddCommand($dbAdapter));
$app->add(new Shuv\CompleteCommand($dbAdapter));

$app->run();